variables:
  DOCKER_HOST: tcp://localhost:2375

stages:          # List of stages for jobs, and their order of execution
  - build
  #- test
  #- deploy
  - push

workflow:
  rules:
    - changes:
      - src/**/*
      - package.json
      - package-lock.json


include:
  - project: zs/devops
    ref: master
    file: pipeline/dind/dind2.gitlab-ci.yml