version: '3'

services:
  api:
    build: .
    #container_name: nodejs-api-container
    restart: always
    env_file: 
      - environment/.env  
    environment:
      - MYSQL_LP_USER=${MYSQL_LP_USER}
      - MYSQL_LP_PASS=${MYSQL_LP_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_PORT=${NODE_PORT}
    networks:
      - backend

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3350:3350
    networks:
      - backend      
networks:
  backend: