version: '3'

services:
  api:
    build: .
    restart: always
    expose:
      - "3350"
    env_file:
      - environment/.env
    environment:
      - MYSQL_LP_USER=${MYSQL_LP_USER}
      - MYSQL_LP_PASS=${MYSQL_LP_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_PORT=${NODE_PORT}
      - VIRTUAL_HOST=nodeapi.vjdev.xyz
      - LETSENCRYPT_HOST=nodeapi.vjdev.xyz
      - VIRTUAL_PORT=3350
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - $HOME/mysql/mysql57-data/_data:/var/lib/mysql
networks:
  default:
    external:
      name: nginx-proxy