version: '3'

services:
  api:
    build: .
    container_name: nodejs-api-container
    restart: always
    ports:
      - "3350:3350"
    env_file:
      - enviroment/.env
    environment:
      - MYSQL_LP_USER=${MYSQL_LP_USER}
      - MYSQL_LP_PASS=${MYSQL_LP_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_PORT=${NODE_PORT}
    networks:
      - backend
    depends_on:
      - mysql_db
      - minio_s3
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - $HOME/mysql/mysql57-data/_data:/var/lib/mysql
    networks:
      - backend
  minio_s3:
    image: 's3backup'
    restart: always
    container_name: minio_s3
    ports:
      - '9000:9000'
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_data
    networks:
      - backend
volumes:
  minio_data:
    driver: local
networks:
  backend: